# Generated by Django 3.1.3 on 2020-11-30 15:01

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('badge', models.ImageField(help_text='Add badge image for this type of item.', upload_to=item.models.upload_menu_type_badge_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'webp'])])),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(help_text='Add features, specialities or uniqueness about the item.', max_length=512)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='in grams', max_digits=8, null=True)),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, help_text='in kCal', max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='in Rupees', max_digits=8)),
                ('is_veg', models.BooleanField(verbose_name='Is vegetarian item?')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available on store?')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='in %', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MenuItemCreator', to=settings.AUTH_USER_MODEL)),
                ('menu_item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MenuItemGroup', to='item_group.menuitemgroup')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MenuItemModifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.ManyToManyField(help_text='You can select multiple item types.', to='item.ItemType')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelMenuItemForType', to='item.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Type',
                'verbose_name_plural': 'Menu Item Types',
            },
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=item.models.upload_menu_item_media_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'webp'])])),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelMenuItemForImage', to='item.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Image',
                'verbose_name_plural': 'Menu Item Images',
            },
        ),
    ]
