# Generated by Django 3.1.3 on 2020-11-29 14:41

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('badge', models.ImageField(upload_to=item.models.upload_menu_type_badge_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(max_length=512)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='in grams', max_digits=8, null=True)),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, help_text='in kCal', max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='in Rupees', max_digits=8)),
                ('is_veg', models.BooleanField()),
                ('is_available', models.BooleanField(default=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='in %', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MenuItemCreator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MenuItemModifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.ManyToManyField(to='item.ItemType')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelMenuItemForType', to='item.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=item.models.upload_menu_item_media_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelMenuItemForImage', to='item.menuitem')),
            ],
        ),
    ]
