# Generated by Django 3.1.3 on 2020-11-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'Item Type', 'verbose_name_plural': 'Item Types'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='menuitemimage',
            options={'verbose_name': 'Menu Item Image', 'verbose_name_plural': 'Menu Item Images'},
        ),
        migrations.AlterModelOptions(
            name='menuitemtype',
            options={'verbose_name': 'Menu Item Type', 'verbose_name_plural': 'Menu Item Types'},
        ),
    ]
