# Generated by Django 3.1.4 on 2021-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Item Type', 'verbose_name_plural': 'Item Types'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='topandrecommendeditem',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Top and Recommended Item', 'verbose_name_plural': 'Top and Recommended Items'},
        ),
        migrations.AddField(
            model_name='itemtype',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topandrecommendeditem',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
