# Generated by Django 3.1.3 on 2020-11-29 15:27

import django.core.validators
from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20201129_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='badge',
            field=models.ImageField(help_text='Add badge image for this type of item.', upload_to=item.models.upload_menu_type_badge_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(help_text='Add features, specialities or uniqueness about the item.', max_length=512),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is available on store?'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(verbose_name='Is vegetarian item?'),
        ),
        migrations.AlterField(
            model_name='menuitemimage',
            name='image',
            field=models.ImageField(upload_to=item.models.upload_menu_item_media_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='menuitemtype',
            name='item_type',
            field=models.ManyToManyField(help_text='You can select multiple item types.', to='item.ItemType'),
        ),
    ]
