# Generated by Django 3.1.3 on 2020-12-19 07:21

import django.core.validators
from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_menuitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='', upload_to=item.models.upload_menu_item_media_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'webp'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, help_text='Add features, specialities or uniqueness about the item.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=False, verbose_name='Is vegetarian item?'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in grams for regular item and ml for bar item', max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='MenuItemImage',
        ),
    ]
