# Generated by Django 3.1.3 on 2020-12-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20201219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemtype',
            name='menu_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RelMenuItemForType', to='item.menuitem'),
        ),
    ]
