# Generated by Django 3.1.3 on 2020-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20201219_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.ManyToManyField(blank=True, help_text='You can select multiple item types.', null=True, to='item.ItemType'),
        ),
        migrations.DeleteModel(
            name='MenuItemType',
        ),
    ]
