# Generated by Django 3.1.3 on 2020-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20201219_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='scale',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Scale for price i.e. how much (quantity / weight(ml)) on this price?', max_digits=8),
        ),
    ]
