# Generated by Django 3.1.3 on 2020-12-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_menuitem_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='scale',
            field=models.IntegerField(default=1, help_text='Scale for price i.e. how much (quantity / weight(ml)) on this price?'),
        ),
    ]
