# Generated by Django 3.1.3 on 2020-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20201219_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.ManyToManyField(blank=True, help_text='You can select multiple item types.', null=True, to='item.ItemType'),
        ),
    ]
