# Generated by Django 3.1.3 on 2020-12-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_group', '0006_auto_20201220_0124'),
        ('item', '0010_auto_20201219_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='item_group.menuitemgroup'),
        ),
    ]
