# Generated by Django 3.1.3 on 2020-12-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20201220_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.ManyToManyField(blank=True, help_text='You can select multiple item types.', related_name='item_types', to='item.ItemType'),
        ),
    ]
