# Generated by Django 3.1.4 on 2020-12-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20201226_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='detail',
            field=models.CharField(editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='log',
            name='mode',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('start', 'Delivery Started'), ('complete', 'Delivery Completed')], editable=False, max_length=8),
        ),
    ]
