# Generated by Django 3.1.4 on 2020-12-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_by',
        ),
    ]
