# Generated by Django 3.1.3 on 2020-12-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_total_items'),
        ('transaction', '0002_auto_20201130_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TransactionOrder', to='cart.order'),
        ),
    ]
