# Generated by Django 3.1.3 on 2020-12-21 16:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
