# Generated by Django 3.1.3 on 2020-12-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemgroup',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='menuitemgroup',
            name='price',
        ),
    ]
