# Generated by Django 3.1.3 on 2020-12-19 07:14

import django.core.validators
from django.db import migrations, models
import item_group.models


class Migration(migrations.Migration):

    dependencies = [
        ('item_group', '0002_auto_20201218_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemgroup',
            name='image',
            field=models.ImageField(default='', upload_to=item_group.models.upload_menu_item_group_media_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'webp'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitemgroup',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='MenuItemGroupImage',
        ),
    ]
