# Generated by Django 3.1.3 on 2020-12-19 19:31

import django.core.validators
from django.db import migrations, models
import item_group.models


class Migration(migrations.Migration):

    dependencies = [
        ('item_group', '0003_auto_20201219_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=item_group.models.upload_menu_item_group_media_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'webp'])]),
        ),
    ]
