# Generated by Django 3.1.4 on 2021-01-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderkot',
            name='quantity_diff',
            field=models.BigIntegerField(default=0, help_text='Quantity difference from previous batch of this KOT item'),
        ),
    ]
