# Generated by Django 3.1.4 on 2021-08-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='orderkot',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Order KOT', 'verbose_name_plural': 'Order KOTs'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
