# Generated by Django 3.1.4 on 2020-12-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
