# Generated by Django 3.1.4 on 2020-12-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
