# Generated by Django 3.1.4 on 2021-01-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderkot_quantity_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done_from_customer_at',
            field=models.DateTimeField(null=True),
        ),
    ]
