# Generated by Django 3.1.4 on 2020-12-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_auto_20201225_0130"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_completed_at",
        ),
    ]
