# Generated by Django 3.1.4 on 2020-12-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_order_order_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_completed",
        ),
    ]
