# Generated by Django 3.1.3 on 2020-11-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201130_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_location',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
