# Generated by Django 3.1.4 on 2020-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201226_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalesreport',
            name='date',
            field=models.CharField(max_length=7),
        ),
    ]
