# Generated by Django 3.1.4 on 2020-12-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201226_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalesreport',
            old_name='count',
            new_name='sale_count',
        ),
    ]
