# Generated by Django 3.1.3 on 2020-12-20 15:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_custom_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_location',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
