# Generated by Django 3.1.4 on 2021-01-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_orderkot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderkot",
            name="quantity",
        ),
    ]
