# Generated by Django 3.1.3 on 2020-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20201220_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
