# Generated by Django 3.1.3 on 2020-12-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
