# Generated by Django 3.1.3 on 2020-12-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_custom_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
