# Generated by Django 3.1.3 on 2020-12-22 01:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20201222_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_location',
            field=models.CharField(max_length=512),
        ),
    ]
