# Generated by Django 3.1.3 on 2020-12-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20201222_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
