# Generated by Django 3.1.3 on 2020-12-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20201222_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash')], default='Cash', max_length=20),
        ),
    ]
