# Generated by Django 3.1.3 on 2020-12-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done_from_customer',
            field=models.BooleanField(default=False),
        ),
    ]
