# Generated by Django 3.1.4 on 2021-08-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'ordering': ['-created_at']},
        ),
    ]
